{% set name = "pymatnest" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/libAtoms/{{ name }}/archive/master.zip
  sha256: c048ea2c885eed7d92e25d00988eec09b452bfc076ee329a1d1b600e16eb83be
  patches:
    - arch.patch

build:
  number: 5
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
  host:
    - python
  run:
    - python
    - ase
    - psutil 
    - mpi4py
    - numpy

test:
  imports:
    - ns_analyse
    - ns_run

about:
  home: https://github.com/libAtoms/pymatnest
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: 'Nested Sampling code'

  description: |
    The pymatnest package is a software library for carrying out 
    nested sampling calculations. It can be used to explore the 
    energy landscape of different materials (both clusters and 
    bulk materials), calculate thermodynamic variables at arbitrary 
    temperatures, locate phase transitions and calculate the phase 
    diagram. It can be used with LAMMPS, QUIP, and the supplied 
    fortran models, and both with MC and MD.
  doc_url: http://libatoms.github.io/pymatnest/
  dev_url: https://github.com/libAtoms/pymatnest

extra:
  recipe-maintainers:
    - jan-janssen
